### ISSUE TITLE
AI Accelerator README.md needs next steps 

### ISSUE THREAD

**Issue by hercules08** [drcrook1/AI_Accelerators_Quality#3]
Finished the AI accelerator video series but left wondering what next? Essentially would like to possible add to the documentation and guide users so that they can take the information they learned through the videos and apply them in a scenario which they can test. Or perhaps the goal is to simply serve as a repo for others with domain knowledge to clone and work from?

**Comment by drcrook1** [comment]
I think next step would be to deploy the solution and make it work.  I should add a full 1 click to deploy set of automation.  Adding to backlog.

**Comment by drcrook1** [comment]
Closing this issue as the solution is undergoing massive re-factor and further investment to more "productize" the solution which should cause this to be a non issue.  New Issues have been created to reflect these new changes.
